language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x

env:
  - GO111MODULE=on

go_import_path: github.com/JigneshSatam/parallel

before_install:
  - go get -v golang.org/x/lint/golint

git:
  depth: 1

os: [linux, osx, windows]

script:
  - go test -race -v ./...
